[package]
name = "tezos-dissector"
version = "0.1.0"
authors = ["Vladislav Melnik <vladislav.melnik@simplestaking.com>"]
edition = "2018"
build = "build.rs"

[lib]
name = "tezos_dissector"
path = "src/lib.rs"
crate-type = ["cdylib"]

[build-dependencies]
bindgen = "0.54"
cmake = "0.1"

[dependencies]
libc = "0.2"
lazy_static = "1.4"
serde = { version="1.0", features=["derive"] }
serde_json = "1.0"
bytes = "0.5"

crypto = { version= "0.2", git = "https://github.com/simplestaking/tezedge" }
networking = { version= "0.2", git = "https://github.com/simplestaking/tezedge" }
tezos_messages = { version= "0.2", git = "https://github.com/simplestaking/tezedge" }
tezos_encoding = { version= "0.2", git = "https://github.com/simplestaking/tezedge" }
